### ISSUE TITLE
int uniforms cause a ShaderParseException

### ISSUE THREAD

**Issue by The-PPWD** [Ladysnake/Satin#10]
Description: Using int uniforms causes Minecraft to throw a ShaderParseException.

Reproduce: Implement an integer uniform in a shader with the corresponding uniform being described in the `.../post/NAME.json` and `.../program/NAME.json`.

Environment:
 - Minecraft Version: 1.16.4
 - Satin Version: 1.5.1
 - Inside or Outside of a development environment: Inside.

Expected behavior: A ShaderParseException shouldn't be thrown and the int uniform should behave like a float uniform (which work).

Screenshots:
![Exception](https://user-images.githubusercontent.com/47865452/100543831-03d7a480-3218-11eb-9340-eca0216bf501.png)
![.../post/filter.json](https://user-images.githubusercontent.com/47865452/100543837-0a661c00-3218-11eb-92bd-fc56ebf8c77f.png)
![.../program/filter.json](https://user-images.githubusercontent.com/47865452/100543851-1a7dfb80-3218-11eb-86cc-fe16a39946e6.png)

**Comment by Pyrofab** [comment]
Thanks for the quality report ! As far as I can tell, this issue no longer occurs in MC 1.17, so I'll close it. Feel free to reopen if that is not the case.
