### ISSUE TITLE
[Question] Can you make a shader localized to a specific area of the world?

### ISSUE THREAD

**Issue by CammiePone** [Ladysnake/Satin#11]
I'm wondering if Satin would allow me to create a distortion shader located at a specific point in the world, or if it only supports camera shaders. I can't really use Canvas as an option, which I know supports them, as I need something that works with Sodium, which I'm hoping Satin works with.

**Comment by Pyrofab** [comment]
Depends on what you want to do, but you can use the depth buffer in your shader to render things at specific locations like the [depth example mod](https://github.com/Ladysnake/Satin/tree/master/test_mods/depth)

**Comment by CammiePone** [comment]
Specifically I'm wanting to add it to an entity. I'll take a look at the depth example, though. Thanks

**Comment by Pyrofab** [comment]
If you want to make an entity render with a shader, you can use the render layer helpers, like the [render layer example mod](https://github.com/Ladysnake/Satin/blob/master/test_mods/render-layer/src/main/java/ladysnake/satinrenderlayer/SatinRenderLayer.java).
