### ISSUE TITLE
Sometimes having multiple shaders active can cause nothing to be rendered

### ISSUE THREAD

**Issue by williambl** [Ladysnake/Satin#13]
**Describe the bug**
In some circumstances, having multiple shaders active can cause nothing (i.e. blackness) to be rendered.

**To Reproduce**
1. Install Haema and Crimson Moon
2. Turn into a vampire.
3. do `/time set night` enough times until a Crimson Moon is triggered

**Environment:**
 - Minecraft Version: 1.16.4
 - Satin Version: 1.4.1
 - Haema Version: compiled from latest commit
 - Crimson Moon Version: compiled from latest commit
 - Development environment: Outside, though has been reproduced in a dev environment

**Screenshots (optional)**
![shows the black screen, with hud still visible](https://camo.githubusercontent.com/8e2281fd45a7613e901da47289087d659fb1f7a1700423f362c28627d6a5c6b9/68747470733a2f2f7577752e666f756e646174696f6e2f36537538665a352e706e67)

**Additional context**
I did at first trigger this with only Haema, but that was in dev and I never committed the changes that caused it to break - there were two shaders active at once. I merged the shaders into one and everything was fine.

**Prior discussion**

[williambl/haema#20](https://github.com/williambl/haema/issues/20)
[Draylar/crimson-moon#15](https://github.com/Draylar/crimson-moon/issues/15)
[conversation 1 on Ladysnake discord](https://discord.com/channels/292744693803122688/477596862031855621/788057907547602985)
[conversation 2 on Ladysnake discord](https://discord.com/channels/292744693803122688/477579058369134593/794602381999603742)
[conversation 3 on Ladysnake discord](https://discord.com/channels/292744693803122688/477579058369134593/797929306734067792)

[Haema's shader](https://github.com/williambl/haema/blob/master/src/main/resources/assets/haema/shaders/post/vampirevision.json)
[Crimson Moon's shader](https://github.com/Draylar/crimson-moon/blob/1.16.2/src/main/resources/assets/crimsonmoon/shaders/post/crimson.json)

**Comment by Pyrofab** [comment]
Looks like this is caused by Crimson Moon bundling an incompatible version of Satin. A workaround is to manually install the latest 1.16 version of the libary in the mods folder.
