### ISSUE TITLE
Significally FPS drop with Vivecraft mod

### ISSUE THREAD

**Issue by VirtualZer0** [Ladysnake/Satin#27]
**Describe the bug**
When playing with Vivecraft mod in VR mode FPS drops to 20-30 from 120. At the same time in Desktop mode, this behavior is not repeated.

**To Reproduce**
Install Vivecraft and Satin API, run game in VR mode

**Environment:**
Minecraft 1.19.2
Vivecraft 0.0.13
Satin API 1.9.0

**Additional context**
I suppose a fix might be extremely difficult, so if possible add at least a warning to the mod. Finding the mod that caused the lag took a very long time, since libraries were the last thing I thought about.

**Comment by G4RYGIT** [comment]
Workaround is to turn eye stencil off in VR settings.

**Comment by an4555** [comment]
Workaround works, but Zer0 is right about a warning or something. Took FOREVER tracking this down

**Comment by Pyrofab** [comment]
Thanks for the report, version 1.18.0 for MC 1.20.5 adds a warning in the logs when both mods are loaded together.
