### ISSUE TITLE
Error loading class: net/coderbot/iris/layer/IrisRenderTypeWrapper

### ISSUE THREAD

**Issue by radiok** [Ladysnake/Satin#30]
**Describe the bug**
Satin is generating warnings regarding IrisRenderTypeWrapper which was removed from Iris with the release of [1.2.5](https://github.com/IrisShaders/Iris/blob/1.16.5/docs/changelogs/1.2.5/full.md).

**To Reproduce**
Setup environment as specified below, you can see the following warnings during Minecraft load.

[main/WARN]: Error loading class: net/coderbot/iris/layer/IrisRenderTypeWrapper (java.lang.ClassNotFoundException: net/coderbot/iris/layer/IrisRenderTypeWrapper)
[main/WARN]: @Mixin target net.coderbot.iris.layer.IrisRenderTypeWrapper was not found mixins.satin.client.json:iris.IrisRenderLayerWrapperMixin from mod satin

**Environment:**
 - Minecraft 1.19.3
 - Fabric Loader 0.14.19
 - Sodium 0.4.9+build.23
 - Satin 1.10.0
 - Iris 1.5.2 (any version greater than 1.2.5 as well)

**Comment by Pyrofab** [comment]
Should be fixed now
