### ISSUE TITLE
Effective 1.4 crashes with Satin 1.9.1, Fabric 0.14.24, Minecraft 1.19.2 

### ISSUE THREAD

**Issue by Fade-Alchemist** [Ladysnake/Satin#44]
While using Minecraft 1.19.2 and Fabric 0.14.24, Effective 1.4 paired with Satin 1.9.1 will crash with error code 1 on startup.
Satin 1.9.0 paired with Effective 1.4 does not crash and starts correctly

The crash and log files are attached.

[crash-2024-01-02_11.55.52-client.txt](https://github.com/Ladysnake/Satin/files/13815023/crash-2024-01-02_11.55.52-client.txt)
[2024-01-02-2.log.gz](https://github.com/Ladysnake/Satin/files/13815028/2024-01-02-2.log.gz)

**Comment by Pyrofab** [comment]
Yea that version seems to cause trouble to quite a few people, so I marked it as beta on modrinth and curseforge

**Comment by Fade-Alchemist** [comment]
This issue is still occurring with Satin 1.9.2
