### ISSUE TITLE
1.20.5 Update

### ISSUE THREAD

**Issue by bruh1273** [Ladysnake/Satin#45]
**Describe your suggestion**
Hello, I have a mod that I always develop, and I use Satin as a library in my mod, and I'd like to port it to 1.20.5, the problem is that this mod hasn't been updated, so I physically cannot do anything until this has been updated. I assume this is the case for many mods alike. 

Thank you in advance for considering this!

**Comment by Pyrofab** [comment]
Hello, sorry for the updating delay. I have already started the port to 1.20.5, but I had to deal with quite a few things last week - I aim to release the new Satin tonight.

**Comment by unwit** [comment]
1.20.6 was recently released to hotfix a minor bug, do you think you could update Satin @Pyrofab?
Thanks!

**Comment by Pyrofab** [comment]
I mean, I am 99.9% sure it Just Works, but sure I can bump the versions on modrinth and curseforge

**Comment by Pyrofab** [comment]
Done
