### ISSUE TITLE
Add 1.21.1 to supported versions of 2.0.0 on MR and CF

### ISSUE THREAD

**Issue by Poopooracoocoo** [Ladysnake/Satin#51]
Update the metadata of 2.0.0 to add 1.21.1 as a supported version. 

https://modrinth.com/mod/satin-api/version/2.0.0
https://www.curseforge.com/minecraft/mc-mods/satin-api/files/5425358

As we know, 1.21.1 was just a hotfix that only fixed two bugs. As there's no strict Minecraft version constraint in the FMJ (which maybe isn't such a good thing), only the metadata needs to be changed.

---

Consider updating the description of Satin API. The FAQ seems rather outdated.

**Comment by Pyrofab** [comment]
Yep, done. Also what would you want to see in the FAQ ?

**Comment by Poopooracoocoo** [comment]
Thanks! 

The Canvas Shader mod reference is outdated. Canvas hasn't seen updates in while. Iris is maintained. Likewise, Secrets No More is no longer maintained.

**Comment by Pyrofab** [comment]
Canvas still has maintainers actually, it has a WIP port to 1.21 and most importantly I still think it's a neat project that deserves attention. That said, you're right that Iris should be mentioned as the main optifine alternative.
As for Secrets No More, do you know an up-to-date alternative ?
