### ISSUE TITLE
JitPack Builds Fail

### ISSUE THREAD

**Issue by gudenau** [Ladysnake/Satin#6]
**Describe the bug**
JitPack build is broken because of a "license violation" in `FramebufferWrapper`, `ManagedUniformBase`, `RenderLayerDuplicator`, `ManagedSamplerUniform`, `ManagedFramebuffer`, `RenderLayerHelper.`, `RenderLayerAccessor`, `MultiPhaseAccessor`, `MultiPhaseParametersAccessor` and `JsonGlProgramAccessor`.

**To Reproduce**
[Have the log.](https://jitpack.io/com/github/Ladysnake/Satin/1.16-1.1.0-SNAPSHOT-gb171511-82/build.log)

**Environment:**
 - Minecraft Version: 1.16-pre2
 - Satin Version: 1.16-SNAPSHOT
 - Inside or Outside of a development environment ? Development

**Comment by Pyrofab** [comment]
https://github.com/Ladysnake/Satin/releases/tag/1.4.0-nightly.1.16-pre2%2Bbuild.1 should work =)
